name: Hugo Check for broken links
description: Checks a Hugo site for broken links
branding:
  color: red
  icon: external-link

inputs:
  fail-on-broken-links:
    required: false
    default: '1'
    description: The number of required broken links to fail the action. Set to 0 to deactivate. Defaults to 1.
  log-skipped-links:
    required: false
    default: 'false'
    description: Logs skipped links and sends them to skipped-links output
  retry:
    required: false
    default: 'true'
    description: Automatically retry requests that return HTTP 429 responses and include a 'retry-after' header
  timeout:
    required: false
    default: '5000'
    description: Request timeout in ms. Set to 0 for no timeout. Defaults to 5000
  skip:
    required: false
    default: ''
    description: List of urls in regexy form to not include in the check
  hugo-root:
    required: true
    description: Base path to your hugo project.
    default: ./
  hugo-content-dir:
    required: true
    description: Base path to your hugo content directory.
    default: ./content
  hugo-config:
    required: true
    description: Base path to your hugo config.
    default: ./config.yaml
  hugo-startup-wait-time:
    required: true
    default: '20'
    description: Maximum time to wait for hugo to start up and process your project.
outputs:
  broken-links-count:
    description: The number of broken links found
  broken-links:
    description: JSON array of broken links
  skipped-links-count:
    description: The number of skipped links found, optional only when log-skipped-links is true
  skipped-links:
    description: JSON array of skipped links, optional only when log-skipped-links is true
runs:
  using: docker
  image: Dockerfile
  env:
    HUGO_ROOT: ${{ inputs.hugo-root }}
    HUGO_CONTENT_DIR: ${{ inputs.hugo-content-dir }}
    HUGO_CONFIG: ${{ inputs.hugo-config }}
    HUGO_STARTUP_WAIT_TIME: ${{ inputs.hugo-startup-wait-time }}
    FAIL_ON_BROKEN_LINKS: ${{ inputs.fail-on-broken-links }}
    LOG_SKIPPED_LINKS: ${{ inputs.log-skipped-links }}
    RETRY: ${{ inputs.retry }}
    TIMEOUT: ${{ inputs.timeout }}
    SKIP: ${{ inputs.skip }}
